---
openapi: 3.0.1
info:
  title: twitter API
  version: v1
paths:
  "/api/v1/oauth/token":
    post:
      summary: 'Get access token '
      tags:
      - Access tokens
      parameters: []
      responses:
        '200':
          description: sessions created
          content:
            application/json:
              examples:
                when new access token is obtained:
                  value:
                    access_token: YLcN_Pj9r6UsQE7qvWrgzdAfjLWYGzFGTB7t8qJTVxM
                    token_type: Bearer
                    expires_in: 7200
                    refresh_token: GaCQyPBEbX7iezbuxpuh1oeR0fODFQecAYCy6Pdenew
                    created_at: 1716629809
                    user_id: 1
                when token is refreshed:
                  value:
                    access_token: COpGglb6rYhct9DLG_Vme2JPUAD1mOmg_a8hul9y7-w
                    token_type: Bearer
                    refresh_token: SFHbBi3nNkjtMP4f_XfN2wC15OTY5e2GpFQcW00A1AE
                    created_at: 1716629809
                    user_id: 2
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  created_at:
                    type: integer
                  expires_in:
                    type: integer
                  token_type:
                    type: string
                  user_id:
                    type: integer
        '400':
          description: invalid grant
          content:
            application/json:
              examples:
                when params are invalid:
                  value:
                    error:
                      code: invalid_request
                      details:
                      - key: _base
                        message: 'Missing required parameter: grant_type.'
                when invalid email or password:
                  value:
                    error:
                      code: authentication
                      details:
                      - key: _base
                        message: The authorization server encountered an unexpected
                          condition which prevented it from fulfilling the request.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                email:
                  type: string
                password:
                  type: string
                grant_type:
                  type: string
              required:
              - scope
              - grant_type
            examples:
              access_token_as_user:
                summary: Obtain access token as user
                value:
                  email: john.doe@example.com
                  password: password
                  scope: user
                  grant_type: password
              refresh_token:
                summary: Refresh access token
                value:
                  refresh_token: RMFTakb-8kWVknGmqAHsmvWrY_aUXpBc4N2-GdHOC6I
servers:
- url: ''
  variables:
    defaultHost:
      default: ''
components:
  securitySchemes:
    Bearer Token:
      description: Access token necessary to use API calls
      type: http
      scheme: bearer
      name: Authorization
      in: header
  schemas: {}
